name: sdc-behavioral-cloning
channels:
- conda-forge
dependencies:
- pip >= 9
- jupyter
- matplotlib
- numpy
- scipy
- scikit-learn
- pandas
- menpo::opencv3
- pip:
  - tensorflow >= 0.12.0rc1
  - keras
- flask-socketio
- eventlet
- pillow
- h5py
